'use strict';

// ---------------------------------------------------------------
// Add tracks/artists to the vault, verify-first.
//
// This is the shared engine behind every content-addition path:
//   - CLI:   node scripts/add_tracks.js "<url-or-id> [--artist=NAME]"
//            node scripts/add_tracks.js --file=tracks.json
//   - Admin: the /api/admin/add endpoint shells this same logic (via addFromSpec)
//
// It always works like the rest of the pipeline: a video is only ever kept if
// the keyless oEmbed truth-check proves it playable AND its real title/author
// round-trip. Nothing unverified ships.
// ---------------------------------------------------------------

const fs = require('fs');
const path = require('path');
const { probeVideo } = require('../lib/checkYouTube');

const ROSTER_PATH = path.join(__dirname, 'vault_roster.json');
const HARVEST_PATH = path.join(__dirname, 'harvested.json');
const GUEST = '(As-Yet-Unconfirmed)';

// "https://www.youtube.com/watch?v=ABC123" | "https://youtu.be/ABC123" | "ABC123"
function parseVideoRef(input) {
  const s = String(input).trim();
  const m = s.match(/(?:v=|youtu\.be\/|shorts\/|embed\/|\/)([A-Za-z0-9_-]{11})(?:[?&#]|$)/);
  if (m) return m[1];
  if (/^[A-Za-z0-9_-]{11}$/.test(s)) return s;
  return null;
}

function loadRoster() {
  try { return JSON.parse(fs.readFileSync(ROSTER_PATH, 'utf8')); }
  catch { return { _note: 'Generated by add_tracks.js', artists: [], tracks: [] }; }
}

function slugOf(name) {
  return name.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function initialsOf(name) {
  return name.split(/[&\s]+/).filter(Boolean).map(w => w[0] && w[0].toUpperCase()).filter(Boolean).slice(0, 3).join('') || name.slice(0, 1).toUpperCase();
}

function upsertArtist(roster, name) {
  let artist = roster.artists.find(a => a.name.toLowerCase() === name.toLowerCase());
  if (!artist) {
    artist = { slug: slugOf(name), name, initials: initialsOf(name), tag: 'Unreleased & Vault' };
    roster.artists.push(artist);
  }
  return artist;
}

// Verify a video and pull its real title/author. Returns null if not playable.
async function verify(id, apiKey) {
  const probe = await probeVideo(id, { apiKey, fetchImpl: fetch });
  if (probe.status !== 'active') return null;
  // Pull authoritative title/author from oEmbed for a clean, honest title.
  const oembed = await (await fetch(`https://www.youtube.com/oembed?format=json&url=${encodeURIComponent('https://www.youtube.com/watch?v=' + id)}`)).json().catch(() => ({}));
  return {
    id,
    realTitle: (oembed.title || '').replace(/\n/g, ' '),
    realAuthor: oembed.author_name || null,
    duration: probe.duration != null ? probe.duration : null,
  };
}

// Record a verified probe into scripts/harvested.json so build_catalog.js
// (which aborts unless every roster id probes active) accepts the track when
// re-created from a source it already lists. Async-write, additive, deduped.
function registerProbe(probe) {
  let data = {};
  try { data = JSON.parse(fs.readFileSync(HARVEST_PATH, 'utf8')); } catch {}
  if (!Array.isArray(data.probes)) data.probes = [];
  const idx = data.probes.findIndex(p => p.id === probe.id);
  if (idx >= 0) data.probes[idx] = { ...data.probes[idx], ...probe };
  else data.probes.push(probe);
  fs.writeFileSync(HARVEST_PATH, JSON.stringify(data, null, 2));
}

function normalize(s) {
  return String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim();
}

// Add a single verified spec to the roster. spec = { id, url?, artist, title? }
// Returns a status object describing what happened.
async function addOne(roster, spec) {
  const id = parseVideoRef(spec.url || spec.id);
  if (!id) return { status: 'invalid', reason: 'could not parse a YouTube id' };
  if (roster.tracks.some(t => t.id === id)) return { status: 'exists', reason: 'already in roster', id };

  const info = await verify(id);
  if (!info) return { status: 'unplayable', reason: 'not embeddable / not active', id };

  const artistName = (spec.artist || GUEST).trim();
  upsertArtist(roster, artistName);

  const dupe = roster.tracks.find(t => normalize(t.title) === normalize(spec.title));
  let title = (spec.title || '').trim();
  if (!title) title = info.realTitle; // fall back to the verified real title

  roster.tracks.push({ artist: artistName, id, title: title || info.realTitle });
  // Record the verification evidence so build_catalog.js can re-build from a
  // fresh checkout (harvested.json is committed) without aborting.
  registerProbe({
    id,
    status: 'active',
    reason: 'added_via_pipeline',
    realTitle: info.realTitle,
    realAuthor: info.realAuthor,
    duration: info.duration,
  });
  return { status: 'added', id, title, artist: artistName, realTitle: info.realTitle, realAuthor: info.realAuthor };
}

// Build from user-provided specs (URL/ID list with optional artist), writing
// back to vault_roster.json. Returns a per-track report.
async function addFromSpecs(specs) {
  const roster = loadRoster();
  const results = [];
  for (const spec of specs) results.push(await addOne(roster, spec));
  fs.writeFileSync(ROSTER_PATH, JSON.stringify(roster, null, 2) + '\n');
  return results;
}

function parseArgCsv() {
  // Allow "--file=tracks.json" with [{url,artist,title}]
  const fileArg = process.argv.find(a => a.startsWith('--file='));
  if (fileArg) {
    const p = path.resolve(fileArg.slice(7));
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    return Array.isArray(data) ? data : [data];
  }
  // Otherwise: positional URLs/IDs, with optional --artist applies to all.
  const artist = (process.argv.find(a => a.startsWith('--artist=')) || '').slice(9);
  const args = process.argv.slice(2); // drop [node, script]
  const rest = args.filter(a => !a.startsWith('--'));
  return rest.map(url => ({ url, artist: artist || undefined }));
}

async function main() {
  const specs = parseArgCsv();
  if (!specs.length) {
    console.error('Usage: node scripts/add_tracks.js "<url-or-id>" [--artist=NAME] | --file=tracks.json');
    process.exit(1);
  }
  const results = await addFromSpecs(specs);
  for (const r of results) {
    const p = r.status === 'added' ? `✓ added  ${r.artist} — ${r.title}  (${r.id})` : `✗ ${r.status.padEnd(10)} ${r.reason} (${r.id || r.url})`;
    console.log(p);
  }
  const added = results.filter(r => r.status === 'added').length;
  console.log(`\n${added}/${results.length} added. Run the pipeline to ship:`);
  console.log('  npm run db:build  &&  npm run db:sync  &&  npm run db:seed  &&  npm test');
}

if (require.main === module) { main().catch(err => { console.error('[add] failed:', err.message); process.exit(1); }); }
module.exports = { addFromSpecs, parseVideoRef, verify, loadRoster, upsertArtist, slugOf, initialsOf };
