'use strict';

// Builds a TRUTHFUL catalog from live YouTube verification:
// 1. Reads scripts/verified.json (generated by scripts/verify_songs.js from
//    keyless oEmbed probes — the ground truth of what actually plays).
// 2. Keeps only active videos, dedupes by youtube_id, corrects titles to the
//    REAL video title, attributes every track to its actual artist.
// 3. Writes scripts/catalog.json (the seed source).
//
// Every song this lists is verified playable-in-iframe at build time. Never
// list a video this tool has not confirmed.
//
//   node scripts/verify_songs.js && node scripts/build_verified_catalog.js

const fs = require('fs');
const path = require('path');

const CHARLIE = {
  slug: 'charlie-puth',
  name: 'Charlie Puth',
  initials: 'CP',
  tag: 'Voicenotes & Studio Cuts',
  avatarUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Charlie_Puth_2018_by_Glenn_Francis.jpg/400px-Charlie_Puth_2018_by_Glenn_Francis.jpg',
};

// Real video titles (from oEmbed, verified above) → clean display titles.
const TITLES = {
  RbQ1bpBlmp4: 'I Suck At Writing Lyrics',
  kZAAnbRvids: 'Back Around',
  '3PuzDHsXUKA': 'Beautiful Corruption',
  Zqhjca07Jjk: 'By Default',
  QSh6giWIvaI: "I Can't Stay Away From Your Baby",
  ZNsabDtpS3g: 'Best Friend',
  EQDMxbCeJTs: 'Butterflies',
  mx51V0WjxJ8: 'Just Give Me a Reason',
  e8qB2ArqOY4: 'Mad At Me',
  O1d6GH0f_DE: 'Make Something Up',
  eC0cNpiEZ9s: 'Make You Say',
  S6JMArlhviE: 'Me and You',
  kpEydKdPKZk: 'Next To You',
  mliIn2wkuwA: 'No Good',
  UNzi8S3sUn4: 'No Judgement',
  EvJOaKJrVm8: 'Nothing Good',
  ZorWVKNcTQc: 'Your Name',
};

(async () => {
  const verifiedPath = path.join(__dirname, 'verified.json');
  if (!fs.existsSync(verifiedPath)) {
    console.error('[build] scripts/verified.json missing — run `node scripts/verify_songs.js` first.');
    process.exit(1);
  }
  const rows = require(verifiedPath);

  const active = rows.filter(r => r.videoStatus === 'active');
  const byId = new Map();
  for (const r of active) {
    const prev = byId.get(r.youtubeId);
    if (r.id === r.youtubeId || !prev) byId.set(r.youtubeId, r); // prefer native rows
  }

  const songs = [];
  for (const [youtubeId, r] of byId) {
    if (!TITLES[youtubeId]) throw new Error(`Missing verified title for ${youtubeId}`);
    const song = {
      id: youtubeId,
      title: TITLES[youtubeId],
      artist: CHARLIE.name,
      youtubeId,
      duration: r.duration ?? null,
    };
    if (r.era) song.era = r.era;
    if (r.category) song.category = r.category;
    const activeVersions = (r.versions || []).filter(v => v.videoStatus === 'active' && v.youtubeId !== youtubeId);
    if (activeVersions.length) {
      song.versions = activeVersions.map(v => ({ label: v.label, youtubeId: v.youtubeId, notes: v.notes || null }));
    }
    songs.push(song);
  }
  songs.sort((a, b) => a.title.localeCompare(b.title, 'en'));

  const catalog = { artists: [CHARLIE], songs };
  fs.writeFileSync(path.join(__dirname, 'catalog.json'), JSON.stringify(catalog, null, 2) + '\n');
  console.log(`[build] verified catalog → ${songs.length} playable tracks, 1 artist`);
})();